#!/bin/bash

if [ ! -d /sys/class/gpio/gpio7 ]; then echo 7 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio75 ]; then echo 75 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio74 ]; then echo 74 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio12 ]; then echo 12 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio13 ]; then echo 13 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio38 ]; then echo 38 > /sys/class/gpio/export; fi
if [ ! -d /sys/class/gpio/gpio39 ]; then echo 39 > /sys/class/gpio/export; fi

echo out > /sys/class/gpio/gpio7/direction
echo out > /sys/class/gpio/gpio12/direction
echo out > /sys/class/gpio/gpio13/direction
echo out > /sys/class/gpio/gpio38/direction
echo out > /sys/class/gpio/gpio39/direction
echo out > /sys/class/gpio/gpio75/direction
echo 0 > /sys/class/gpio/gpio7/value
echo 0 > /sys/class/gpio/gpio12/value
echo 0 > /sys/class/gpio/gpio13/value
echo 0 > /sys/class/gpio/gpio38/value
echo 0 > /sys/class/gpio/gpio39/value
echo 0 > /sys/class/gpio/gpio75/value

echo in > /sys/class/gpio/gpio74/direction
echo rising > /sys/class/gpio/gpio74/edge
